"""Initial migration

Revision ID: 21a9c664d6d1
Revises: 4d1cb679b519
Create Date: 2024-09-16 00:48:14.349752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21a9c664d6d1'
down_revision = '4d1cb679b519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
